name       : python-nbconvert
version    : 5.5.0
release    : 3
source     :
    - https://github.com/jupyter/nbconvert/archive/5.5.0.tar.gz : 93721d772361d1cd59502dacfb76c4122359b1c321cea1882451532a2db02d59
license    : BSD-3-Clause
component  : programming.python
networking : yes
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - pandoc
    - pygments
    - python-bleach
    - python-defusedxml
    - python-ipykernel
    - python-jinja
    - python-mistune
    - python-nbformat
    - python-pandocfilters
    - python-testpath
    - python-traitlets
    - texlive
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
