name       : python-nbconvert
version    : 6.5.0
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/n/nbconvert/nbconvert-6.5.0.tar.gz : 223e46e27abe8596b8aed54301fadbba433b7ffea8196a68fd7b1ff509eee99d
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
rundeps    :
    - python-beautifulsoup4
    - python-bleach
    - python-defusedxml
    - python-ipykernel
    - python-jinja
    - python-jupyterlab-pygments
    - python-mistune
    - python-nbclient
    - python-packaging
    - python-pandocfilters
    - python-tinycss2
setup      : |
    %python3_setup
install    : |
    %python3_install
