name       : python-nbconvert
version    : 6.4.4
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/n/nbconvert/nbconvert-6.4.4.tar.gz : ee0dfe34bbd1082ac9bfc750aae3c73fcbc34a70c5574c6986ff83c10a3541fd
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
rundeps    :
    - python-bleach
    - python-defusedxml
    - python-ipykernel
    - python-jinja
    - python-jupyterlab-pygments
    - python-mistune
    - python-nbclient
    - python-pandocfilters
    - python-testpath
setup      : |
    %python3_setup
install    : |
    %python3_install
