name       : python-nbconvert
version    : 7.0.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/n/nbconvert/nbconvert-7.0.0.tar.gz : fd1e361da30e30e4c5a5ae89f7cae95ca2a4d4407389672473312249a7ba0060
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
networking : yes
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-beautifulsoup4
    - python-bleach
    - python-defusedxml
    - python-jinja
    - python-jupyterlab-pygments
    - python-lxml
    - python-mistune
    - python-nbclient
    - python-packaging
    - python-pandocfilters
    - python-pyppeteer
setup      : |
    %python3_setup
install    : |
    %python3_install
