name       : python-nbconvert
version    : 5.3.1
release    : 2
source     :
    - https://github.com/jupyter/nbconvert/archive/5.3.1.tar.gz : 0ca7dcaa1f554bfe6e57b218dd4c1e1dd8019e5e3561e865abfc1c6a3bdb4000
license    :
    - BSD-3-Clause
    - MIT
component  : programming.python
networking : yes
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - pandoc
    - pygments
    - python-bleach
    - python-entrypoints
    - python-ipykernel
    - python-jinja
    - python-jupyter_client
    - python-jupyter_core
    - python-mistune
    - python-nbformat
    - python-pandocfilters
    - python-testpath
    - python-tornado
    - python-traitlets
    - texlive
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
