name       : python-nbconvert
version    : 5.6.1
release    : 6
source     :
    - https://github.com/jupyter/nbconvert/archive/5.6.1.tar.gz : 444adfbedfe1f63da86fc74f1f2f317e2555a679b81676b08bf1508142d8010b
license    : BSD-3-Clause
component  : programming.python
networking : yes
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pandoc
    - pygments
    - python-bleach
    - python-defusedxml
    - python-ipykernel
    - python-jinja
    - python-mistune
    - python-nbformat
    - python-pandocfilters
    - python-testpath
    - python-traitlets
    - texlive
setup      : |
    %python3_setup
install    : |
    %python3_install
