name       : python-nbconvert
version    : 7.2.3
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/n/nbconvert/nbconvert-7.2.3.tar.gz : 7ae7ccc68495b565dab153459ee7e65039970913eb115070da6e2c673cf0e9f8
homepage   : https://github.com/jupyter/nbconvert
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Notebook Conversion
description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other formats via Jinja templates. The nbconvert tool allows you to convert an .ipynb notebook file into various static formats.
networking : yes
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-beautifulsoup4
    - python-bleach
    - python-defusedxml
    - python-jinja
    - python-jupyterlab-pygments
    - python-mistune
    - python-nbclient
    - python-packaging
    - python-pandocfilters
    - python-pyppeteer
setup      : |
    %python3_setup
install    : |
    %python3_install
